version: 2
jobs:
  test:
    working_directory: ~/clj-aql
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: clj-aql-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: clj-aql-{{ checksum "project.clj" }}
      - run: lein test
      - store_test_results:
          path: target/test-results
workflows:
  version: 2
  default:
    jobs:
      - test